sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t swpril/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true swpril/react-test npm run test

after_success:
  - docker build -t swpril/multi-client ./client
  - docker build -t swpril/multi-nginx ./nginx
  - docker build -t swpril/multi-worker ./worker
  - docker build -t swpril/multi-server ./server
